### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by CMCDragonkai** [leebyron/spec-md#1]
Great work.
I've been looking for a language that supports all sorts of technical documentation (something like sense.io, but doesn't require server side execution).

My suggestions include:

* Latex support for formulas
* Diagram support including (UML, PlantUML, Dot/Graph) (like http://www.gravizo.com/)

SVGs could be used to support graphs and the like.

**Comment by leebyron** [comment]
Hey, I'm glad you like it, thanks for these suggestions.

One nice thing about markdown is HTML support, so I'm hoping that offers a reasonable extension point that should handle diagram support. It looks like gravizo will output to an image file, which is exactly what you would want for spec-md. They even illustrate markdown syntax, very nice.

Latex support or MathML would also be a really interesting addition. That's not something I've needed, but I can see how more mathy specifications would find that desirable. I would recommend looking at http://khan.github.io/KaTeX/ which can do really nice Latex -> HTML.

Let me know if you end up using spec-md and Latex math support is important to you and we can figure out how to proceed.

**Comment by CMCDragonkai** [comment]
Perhaps there can be hookpoints that can load in extra syntax specifications?

Maybe even a `syntax.json` that defines all the syntax/grammar to load in. The specifications would have to be non-conflicting.

I did some work with OMeta before, and it allowed grammar composition in an OOP way.

**Comment by gappture** [comment]
I have a use case that requires latex support. It would be great if support for this could be built into spec-md! Would make this tool even better!

**Comment by leebyron** [comment]
Closing this since there's no plans to add Formula or Diagram support directly to Markdown, Images are always a reasonable approach.

I'd still entertain PRs which added features like this, though!
