### ISSUE TITLE
TypeError 

### ISSUE THREAD

**Issue by ppKrauss** [leebyron/spec-md#13]
`spec-md Markdown.md`

```
TypeError: Cannot read property 'value' of null
    at printSidebar (/usr/local/lib/node_modules/spec-md/src/print.js:259:61)
    at printBody (/usr/local/lib/node_modules/spec-md/src/print.js:49:5)
    at print (/usr/local/lib/node_modules/spec-md/src/print.js:14:18)
    at /usr/local/lib/node_modules/spec-md/src/index.js:7:12
```

**Comment by homakov** [comment]
Yep. It actually is not working at all.

**Comment by leebyron** [comment]
My best guess is that your document is missing a title. I'll include a more clear error message when this occurs.

**Comment by ppKrauss** [comment]
Hi @leebyron , try your https://github.com/leebyron/spec-md/blob/master/README.md

**Comment by leebyron** [comment]
Yes, the README.md file successfully goes through spec-md, it is used it to build the spec-md website here: https://github.com/leebyron/spec-md/blob/master/package.json#L17
