### ISSUE TITLE
LaTeX support solved

### ISSUE THREAD

**Issue by hermanzdosilovic** [leebyron/spec-md#15]
Hi @leebyron,

I successfully added full LaTeX support by adding this line in `head` of rendered HTML:
```
<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [["$","$"]],displayMath: [["$$","$$"]]},messageStyle: "none"});</script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

I can now use `$` for inline math and `$$` for block math.

I wrote simple [script](https://gist.github.com/hermanzdosilovic/3f57d70d324200851beb174555eefb31) that inserts this line in `head` for me.

Looks like this could be a solution for integrating LaTeX with spec-md. Let me know what you think! :smile:

**Comment by leebyron** [comment]
Very cool. I just added the ability to add content into `<head>` directly so you won't need to maintain the shell magic
