### ISSUE TITLE
Add support for relative file links with space in the file name

### ISSUE THREAD

**Issue by klzns** [leebyron/spec-md#17]
Example of the Markdown code:
https://github.com/klzns/graphql/blob/fix-links/spec/GraphQL.md

And the error that spec-md throws:
https://travis-ci.org/facebook/graphql/builds/339424516

Maybe it should `decodeUri` the link so it can find the file.

Related: https://github.com/facebook/graphql/pull/406

**Comment by leebyron** [comment]
Thanks for the report! In the future don't feel shy about sending a PR. Got this fixed and will pull it into the GraphQL spec repo so we can get your other PR merged
