### ISSUE TITLE
Spec-MD does not operate correctly in Windows

### ISSUE THREAD

**Issue by csuwildcat** [leebyron/spec-md#26]
After hacking for a few hours yesterday (initially from the basis of what appeared to be an error in the Setext title code) to try to get the package running in Windows (even with WSL Ubuntu), I got it half-working, but it's clear there are many issues going on that are resulting in failed or incorrect output in Windows.

Steps to reproduce:

1. Try to parse anything (even basic examples from the repo) in Windows.

**Comment by leebyron** [comment]
I'd love to review a PR for this issue - unfortunately I don't have a Windows machine myself to reproduce this

**Comment by csuwildcat** [comment]
It's cool, I just built a more capable, feature rich, cross-platform solution as a result of not finding anything in the market that wasn't riddled with show-stopping issues: https://identity.foundation/spec-up/

**Comment by csuwildcat** [comment]
And it works on literally every machine that can run Node. You're welcome.

**Comment by leebyron** [comment]
Very cool! Glad to see more tools for writing specs. I'm sure you'll prefer your homegrown solution, but at least Windows support is here for this tool as well.

Turned out to be a pretty straightforward CRLF parsing error
