### ISSUE TITLE
Task lists / checkboxes

### ISSUE THREAD

**Issue by w0k3** [leebyron/spec-md#27]
I can't find any way to make check / [task lists](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#task-lists) work, while they work just fine in other GFM tools.

Is it intended to not support them? Can't they simply be read only or at least ignored (not causing `spec-md` to fail generating a HTML file)? We are using them extensively in our work-in-progress documentation.

**Comment by leebyron** [comment]
I'd love to review a PR for this
