### ISSUE TITLE
Handle <pre> tags verbatim, including newlines and whitespace

### ISSUE THREAD

**Issue by JoelMarcey** [leebyron/spec-md#5]
Given 

```
<pre>
<i>source-unit:</i>
  <i>declaration-list<sub>opt</sub></i>

<i>declaration-list:</i>
  <i>declaration</i>
  <i>declaration-list</i>   <i>declaration</i>

<i>declaration:</i>
  <i>global-constant-declaration</i>
  <i>function-declaration</i>
  <i>class-declaration</i>
  <i>global-type-constant-declaration</i>
  <i>module-declaration</i>
</pre>
```

the output ends up being

![screen shot 2016-10-19 at 7 44 41 am](https://cloud.githubusercontent.com/assets/3757713/19523633/f16c0a04-95cf-11e6-8f6c-0e5bf721c0c0.png)

This gets processed by `htmlTag` in `grammar.pegjs`

```
htmlTag = tag:$('<' '/'? [a-z]+ [^>]* '>') {
  return {
    type: 'HTMLTag',
    tag: tag
  };
}
```

That doesn't take into account whitespace and newlines, and maybe it shouldn't.

So I tried to create a `preTag`, but was having trouble with lookaheads, etc.

I tried both:

```
preTag = tag:$('<pre>' [A-Za-z0-9\:\<\>\/]+ '</pre>') {
  return {
    type: 'PRETag',
    tag: tag
  };
}
```

```
preTag = tag:$('<pre>' !(\<\/pre\>).* '</pre>') {
  return {
    type: 'PRETag',
    tag: tag
  };
}
```

The first one seemed most promising, but the `\<` gets in the way, which is why I tried a negative lookahead option, but the grammar didn't handle that the way I did it.

**Comment by leebyron** [comment]
Ooo, good find. We should probably always preserve whitespace within HTML because I'm sure <pre> isn't the only one with subtle whitespace quirks
