### ISSUE TITLE
Weird scroll bar in pre tags

### ISSUE THREAD

**Issue by nam-hle** [leebyron/spec-md#87]
How the awesome library here :D
I came from GraphQL spec Oct 2021 and saw that the `pre` tags have scroll bars like this:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/28835226/140000811-fad50366-760e-4733-9892-068c8cffa38d.png">
Compare to the previous spec:
<img width="862" alt="image" src="https://user-images.githubusercontent.com/28835226/140000832-0ac8283d-35c9-41b7-8e76-2cc59222f9f7.png">

Is it the library's intention?

**Comment by leebyron** [comment]
Not intentional! Can you share some details of your OS and browser version to help identify what might be going on?

Do you see this in other browsers?

Also, if you have a sense of what might fix it, I'd be happy to take PRs

**Comment by nam-hle** [comment]
Of course, my machine is macOS 10.15.6, the scroll bars appear on Firefox 93.0, Chrome 95.0.4638.69, Safari v14.
The same to virtual Windows 10 - FF 93.0, Edge 95.0.1020.40. 

And yes, my attempt PR will come soon :D
