### ISSUE TITLE
TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by sichvoge** [leebyron/spec-md#9]
Hi,

This tool seems to be very valuable, but I cannot seem to get it working. I have this very simple MD file:

```markdown
# Introduction

Hello
```

and the result for executing `spec-md index.md > index.html` is only the following error:

```
TypeError: Cannot read property 'value' of null
```

Can anyone help me?

My node version is `v7.7.4`.

**Comment by sichvoge** [comment]
Seems it works changing the first line from using `#` to `-----`. Is that really required?

**Comment by leebyron** [comment]
Yes, that's currently required for extracting the first document title http://leebyron.com/spec-md/#sec-Title-and-Introduction

I'd happily entertain PRs to make this more lenient
